"""Run what this repository can run end to end, and write down that it ran.

A repository whose continuous integration is frozen says nothing about itself: the green tick is
two years old, or absent. What replaces it is ``reports/run-evidence.json`` — the exact command,
the day, the revision, the tool versions, what it cost, and the tracked files it produced. A
reader can rerun that command and compare.

**The run must reproduce what the repository publishes.** The step below redraws every published
figure from the committed result artefacts; if any image comes out different from the committed
version, no evidence is written and the differing files are named. That is the whole value of the
exercise: evidence that merely says "it ran" proves that something ran, not that what is
published is what it produces.

    uv run python scripts/smoke.py

What it does not cover, and cannot: training and evaluation. Both need a GPU, the model weights
and the four public corpora, and neither fits in a smoke run. What is reproduced is everything
downstream of them — every figure, from the result files the runs left behind. A reader without
a GPU can still check that the pictures are what the committed numbers produce.

Run it on a clean clone, before the release tag. No workflow writes this file: a committed
artefact regenerated by continuous integration is an artefact whose author is a machine nobody
watches.
"""

from __future__ import annotations

import json
import platform
import shutil
import subprocess
import sys
import time
from datetime import UTC, datetime
from importlib.metadata import PackageNotFoundError, version

from clinical_triage.config import PROJECT_ROOT as ROOT_DIR

EVIDENCE = "reports/run-evidence.json"
COMMAND = "uv run python scripts/smoke.py"

#: The tracked files this run regenerates. Each one is compared with its committed version: a
#: smoke test that writes nothing proves that the process starts, not that it works.
KEY_OUTPUT: tuple[str, ...] = (
    "reports/figures/accuracy_by_case_type.png",
    "reports/figures/confusion_matrices.png",
    "reports/figures/dataset_composition.png",
    "reports/figures/dpo_alignment.png",
    "reports/figures/endpoint_latency.png",
    "reports/figures/hyperparameter_tuning.png",
    "reports/figures/recall_versus_transfer.png",
    "reports/figures/sft_training.png",
    "reports/figures/systems_comparison.png",
    "reports/figures/undertriage_by_case_type.png",
    "reports/figures/MANIFEST.json",
)

#: The distributions whose version changes the result. Not the whole lock file: the reader needs
#: what would explain a different number, not an inventory.
TOOLS: tuple[str, ...] = ("matplotlib", "numpy", "scikit-learn", "fastapi", "pydantic")


def steps() -> None:
    """Redraw every figure from the artefacts the runs wrote.

    Nothing here catches: a step that failed would otherwise leave evidence saying the run
    succeeded.
    """
    for script in ("build_figures.py",):
        done = subprocess.run(
            [sys.executable, f"scripts/{script}"],
            cwd=ROOT_DIR,
            capture_output=True,
            text=True,
            check=False,
        )
        if done.returncode != 0:
            raise RuntimeError(
                f"scripts/{script} failed with code {done.returncode}: "
                f"{done.stdout.strip()[-800:]} {done.stderr.strip()[-800:]}"
            )
        print(f"  {script}")


# --- What the evidence records ----------------------------------------------


def _git(*arguments: str) -> str:
    done = subprocess.run(
        ["git", *arguments], cwd=ROOT_DIR, capture_output=True, text=True, check=False
    )
    return done.stdout.strip()


def tool_versions() -> dict[str, str]:
    versions = {"python": platform.python_version()}
    for name in TOOLS:
        try:
            versions[name] = version(name)
        except PackageNotFoundError:
            versions[name] = "not installed"
    for binary, arguments in (("uv", ("--version",)), ("docker", ("--version",))):
        if shutil.which(binary):
            done = subprocess.run([binary, *arguments], capture_output=True, text=True, check=False)
            versions[binary] = done.stdout.strip() or "unknown"
    return versions


def reproduced() -> list[str]:
    """The key outputs the run did NOT reproduce: missing, untracked, or changed."""
    problems: list[str] = []
    for rel in KEY_OUTPUT:
        if not (ROOT_DIR / rel).exists():
            problems.append(f"{rel} — not produced")
            continue
        if not _git("ls-files", "--error-unmatch", rel):
            problems.append(f"{rel} — produced but not tracked by git")
            continue
        if _git("status", "--porcelain", "--", rel):
            problems.append(f"{rel} — differs from the committed version")
    return problems


def main() -> int:
    if not KEY_OUTPUT:
        print("scripts/smoke.py: name the tracked files this run regenerates", file=sys.stderr)
        return 1

    started = time.monotonic()
    steps()
    duration = round(time.monotonic() - started, 1)

    differences = reproduced()
    if differences:
        print("the run did not reproduce what is published:", file=sys.stderr)
        for line in differences:
            print(f"  {line}", file=sys.stderr)
        print(f"{EVIDENCE} not written", file=sys.stderr)
        return 1

    evidence = {
        "command": COMMAND,
        "ran_at": datetime.now(tz=UTC).date().isoformat(),
        "git_revision": _git("rev-parse", "HEAD"),
        "tool_versions": tool_versions(),
        "duration_seconds": duration,
        "key_output": list(KEY_OUTPUT),
        # Null, and said so: the workflows of this repository are frozen to a manual trigger, so
        # there is no run to point at. A missing key would read as an oversight.
        "workflow_run_url": None,
    }
    target = ROOT_DIR / EVIDENCE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(evidence, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline=""
    )
    print(f"{EVIDENCE} written — {duration}s, {len(KEY_OUTPUT)} output(s) reproduced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
